### PR TITLE
Added "Point" and "UUID"

### PR DESCRIPTION
**Pull request by kevin0571**
PointField will be serialized to { "x": value, "y": value }
Test case is provided.

UUIDField will be serialized with UUID, which is provided by marshmallow itself.

### CODE REVIEW

**Comment by kevin0571** [comment]
Currently does not support 3D point since I only get coordinates[0] and coordinates[1] from PointField.

**Comment by touilleMan** [comment]
Awesome !

**Comment by etrochim** [comment]
What is the reasoning behind serializing PointField to `{ "x": value, "y": value }`? It seems to me that PointField should be serialized to a GeoJSON point object.

**Comment by touilleMan** [comment]
@etrochim no real reason, I think it was from @kevin0571 needs

However you can use `register_field` to overload the mashmallow field to use by a subclass of `PointField` wuth a custom serialization.

**Comment by etrochim** [comment]
The reason I'm asking is because I just discovered this project and thought it might be useful for another project I am working on where I need to serialize mongoengine documents with MultiPolygon and Polygon fields. After finding that those field types were not implemented I decided to implemented them myself but quickly ran into this strange serialization format.

In my mind the default Point, Polygon, LineString, etc fields should serialize to a standard geo interchange format; GeoJSON in particular. If the user requires something different they should go down the subclassing route you suggested.

In the interest of implementing these unimplemented fields, what should the other geo field serialization formats look like? Using a non-standard format built off the current PointField would be useful to few users (because few other tools would recognize that format). However, changing PointField to emit GeoJSON has backward compatibility concerns. I'm curious about what your thoughts are?

**Comment by kevin0571** [comment]
@etrochim the reason I implemented this with x, y instead of longitude, latitude is that I think *Point* in this case is a generic point instead of a geo point, that is why it's described with a coordinate(x, y). Correct me if I'm wrong.

**Pull request merged**
